
# Setup 1
# [cpu]
# temperature = "/sys/class/hwmon/hwmon0/temp1_input"
# temperature_denominator = 1000.0

# Setup 2
[cpu]
temperature = "/sys/class/hwmon/hwmon0/temp1_input"
temperature_denominator = 1000.0

[battery]
percentage = "/sys/class/power_supply/BAT0/capacity"
status = "/sys/class/power_supply/BAT0/status"
